project_name: kubectl-crashwatch
release:
  github:
    owner: bedirhangull
    name: kubectl-crashwatch
builds:
  - id: kubectl-crashwatch
    goos:
    - linux
    - windows
    - darwin
    goarch:
    - amd64
    - "386"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: cmd/plugin/main.go
    ldflags: -s -w
      -X github.com/bedirhangull/kubectl-crashwatch/pkg/version.version=
archives:
  - id: kubectl-crashwatch
    builds:
    - kubectl-crashwatch
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
    - goos: windows
      format: zip
