apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: crashwatch
spec:
  version: "v1.0.3"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/bedirhangull/kubectl-crashwatch/releases/download/v0.1.0/crashwatch_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./crashwatch"
      to: "."
    - from: LICENSE
      to: "."
    bin: "crashwatch"
    
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/bedirhangull/kubectl-crashwatch/releases/download/v0.1.0/crashwatch_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./crashwatch"
      to: "."
    - from: LICENSE
      to: "."
    bin: "crashwatch"

  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/bedirhangull/kubectl-crashwatch/releases/download/v0.1.0/crashwatch_windows_amd64.zip
    sha256: ""
    files:
    - from: "/crashwatch.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "crashwatch.exe"

  shortDescription: A kubectl plugin to monitor CrashLoopBackOff pods
  homepage: https://github.com/bedirhangull/kubectl-crashwatch
  caveats: |
    Usage:
      $ kubectl crashwatch

    For additional options:
      $ kubectl crashwatch --help
      or visit the documentation at https://github.com/bedirhangull/kubectl-crashwatch/blob/v0.1.0/doc/USAGE.md

  description: |
    Crashwatch is a kubectl plugin designed to help users monitor and log all pods that are in a CrashLoopBackOff state within a Kubernetes cluster. Users can also view these pods in a dashboard for easier monitoring and troubleshooting.
