apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: crashwatch
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/bedirhangull/kubectl-crashwatch/releases/download/v0.1.0/crashwatch_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./crashwatch"
      to: "."
    - from: LICENSE
      to: "."
    bin: "crashwatch"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/bedirhangull/kubectl-crashwatch/releases/download/v0.1.0/crashwatch_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./crashwatch"
      to: "."
    - from: LICENSE
      to: "."
    bin: "crashwatch"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/bedirhangull/kubectl-crashwatch/releases/download/v0.1.0/crashwatch_windows_amd64.zip
    sha256: ""
    files:
    - from: "/crashwatch.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "crashwatch.exe"
  shortDescription: A new plugin
  homepage: https://github.com/bedirhangull/kubectl-crashwatch
  caveats: |
    Usage:
      $ kubectl crashwatch

    For additional options:
      $ kubectl crashwatch --help
      or https://github.com/bedirhangull/kubectl-crashwatch/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a new plugin
